version: '3.0'
services:
  web-1:
    build:
      dockerfile: docker/Dockerfile.webapp
      context: .
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
    - "8080:8080"
    depends_on:
      - rabbitmq
  web-2:
    build:
      dockerfile: docker/Dockerfile.webapp
      context: .
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
  rabbitmq:
    build:
      dockerfile: docker/Dockerfile.rabbitmq
      context: .
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 3
    ports:
    - "5672:5672"
    - "61613:61613"
    - "15672:15672"